(cl:defpackage pr2_gazebo_plugins-srv
  (:use )
  (:export
   "SETMODELSJOINTSSTATES"
   "<SETMODELSJOINTSSTATES-REQUEST>"
   "SETMODELSJOINTSSTATES-REQUEST"
   "<SETMODELSJOINTSSTATES-RESPONSE>"
   "SETMODELSJOINTSSTATES-RESPONSE"
  ))

